version: '3'
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - "elasticsearch" # condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=password
    expose:
      - "9200"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 20

  kibana:
    image: kibana:8.1.2
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch" #condition: service_healthy

  #zipkin:
  #  links:
  #    - "elasticsearch"
  #  environment:
  #    - STORAGE_TYPE=elasticsearch
  #    - ES_HOSTS=elasticsearch:9200
  #    # Uncomment to see requests to and from elasticsearch
  #    - ES_HTTP_LOGGING=BODY
volumes:
  elasticsearch_data:
    driver: local

#networks:
#  default:
#    external:
#      name: swa